/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthCallBackHandler: typeof import('./src/components/AuthCallBackHandler.vue')['default']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelectOption']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BOverlay: typeof import('bootstrap-vue-next/components/BOverlay')['BOverlay']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    CountDownTimer: typeof import('./src/components/CountDownTimer.vue')['default']
    CrontabModal: typeof import('./src/components/CrontabModal.vue')['default']
    DisabledJobsModal: typeof import('./src/components/DisabledJobsModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    IBi0Circle: typeof import('~icons/bi/0-circle')['default']
    IBi0Envelope: typeof import('~icons/bi/0-envelope')['default']
    IBiEnvelope: typeof import('~icons/bi/envelope')['default']
    IBiFiles: typeof import('~icons/bi/files')['default']
    IBiMoon: typeof import('~icons/bi/moon')['default']
    IBiSun: typeof import('~icons/bi/sun')['default']
    JobBox: typeof import('./src/components/JobBox.vue')['default']
    LastExecution: typeof import('./src/components/LastExecution.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NewJobModal: typeof import('./src/components/NewJobModal.vue')['default']
    OverdueCounter: typeof import('./src/components/OverdueCounter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendOutputModal: typeof import('./src/components/SendOutputModal.vue')['default']
    SubscriptionModal: typeof import('./src/components/SubscriptionModal.vue')['default']
    TestCronPatternModal: typeof import('./src/components/TestCronPatternModal.vue')['default']
  }
  export interface GlobalDirectives {
    vBModal: typeof import('bootstrap-vue-next/directives/BModal')['vBModal']
  }
}
