services:
  frontend:
    image: cronclient-vuejs
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      ENV: production
      TZ: America/Chicago
      CRON_SERVICE_BASE: 'https://cronservice.outlawdesigns.io'
      MSG_SERVICE_BASE: 'https://messenger.outlawdesigns.io'
      AUTH_DISCOVERY_URI: 'https://auth.outlawdesigns.io/.well-known/openid-configuration'
      AUTH_CLIENT_ID: 'cronsuite-vuepwa'
      AUTH_REDIRECT_URL: 'http://localhost:3000/token/'
      AUTH_LOGOUT_URL: 'http://localhost:3000/logout/'
      AUTH_SCOPE: 'offline_access offline openid'
      GIST_URL: 'https://gist.github.com/outlawstar4761/a1105f79ba4cd26916abce8a0f3bb139'
      AUTH_DISABLED: false
    ports:
      - '3000:8080'
