export default{
  development:{
    CRON_SERVICE_BASE:'http://localhost',
    CRON_SERVICE_PORT:9550,
    MSG_SERVICE_BASE:'https://api.outlawdesigns.io',
    MSG_SERVICE_PORT:9667,
    AUTH_SERVICE_BASE:'https://ubuntuserver.outlawdesigns.io',
    AUTH_SERVICE_PORT:9661
  },
  testing:{
    CRON_SERVICE_BASE:'localhost',
    CRON_SERVICE_PORT:9550,
    MSG_SERVICE_BASE:'localhost',
    MSG_SERVICE_PORT:9667,
    AUTH_SERVICE_BASE:'localhost',
    AUTH_SERVICE_PORT:9661
  },
  production:{
    CRON_SERVICE_BASE:'https://ubuntuserver.outlawdesigns.io',
    CRON_SERVICE_PORT:9550,
    MSG_SERVICE_BASE:'https://api.outlawdesigns.io',
    MSG_SERVICE_PORT:9667,
    AUTH_SERVICE_BASE:'https://ubuntuserver.outlawdesigns.io',
    AUTH_SERVICE_PORT:9661
  }
}
